In [1]:
import numpy as np

In [8]:
print('Hello Numpy')

a=np.array(range(5))

print(a)

print(a.dtype)

print(a.ndim)

print(a.size)

print(a.shape)

# 2-dimentional array

b=np.array([range(5),range(5,0,-1)])

print(b)

print(b.dtype)

print(b.ndim)

print(b.size)

print(b.shape)

# 3- dimentional array
c=np.array([[range(5),range(5,0,-1)],[range(5),range(5,0,-1)]])

print(c)

print(c.dtype)

print(c.ndim)

print(c.size)

print(c.shape)



Hello Numpy
[0 1 2 3 4]
int32
1
5
(5,)
[[0 1 2 3 4]
 [5 4 3 2 1]]
int32
2
10
(2, 5)
[[[0 1 2 3 4]
  [5 4 3 2 1]]

 [[0 1 2 3 4]
  [5 4 3 2 1]]]
int32
3
20
(2, 2, 5)


In [9]:
# intrinsic creation of arrays

d=np.zeros((3,3),dtype=complex)

print(d)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [11]:
e=np.ones((3,3),dtype=float)

print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
f=np.array(np.arange(0,6).reshape(3,2),dtype=complex)

print(f)

print(f.ndim)

[[0.+0.j 1.+0.j]
 [2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j]]
2


In [16]:
np.arange(0,14).reshape(7,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [22]:
#linspecing

np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [31]:
# random funcation

print(np.random.random(10))

np.random.random((5,5))

[0.8070434  0.78398988 0.09297565 0.20298822 0.45253509 0.81381722
 0.95055635 0.15780358 0.41904436 0.58262913]


array([[0.61585057, 0.64690535, 0.6690635 , 0.46684269, 0.40419999],
       [0.05338823, 0.17171296, 0.5852445 , 0.21241634, 0.05402084],
       [0.19610853, 0.95878923, 0.08306742, 0.03522876, 0.6340955 ],
       [0.5104232 , 0.02913268, 0.33599314, 0.01073041, 0.582835  ],
       [0.29042821, 0.36373112, 0.71358645, 0.32520416, 0.20131832]])

In [39]:
# arithematic operations
f=np.arange(3,15)

print(f)

print(f+4)

print(f-1)

print(f*5)

print(f/3)

print(f%3)

print(f*np.sin(np.arange(3,15)))


[ 3  4  5  6  7  8  9 10 11 12 13 14]
[ 7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13]
[15 20 25 30 35 40 45 50 55 60 65 70]
[1.         1.33333333 1.66666667 2.         2.33333333 2.66666667
 3.         3.33333333 3.66666667 4.         4.33333333 4.66666667]
[0 1 2 0 1 2 0 1 2 0 1 2]
[  0.42336002  -3.02720998  -4.79462137  -1.67649299   4.59890619
   7.91486597   3.70906637  -5.44021111 -10.99989227  -6.43887502
   5.46217148  13.86850298]


In [54]:
g=np.array([np.arange(3,9),np.arange(8,2,-1)],dtype=float)
print(g)

for row in g:
    print(row)

for row in g.flat:
    print(row)

[[3. 4. 5. 6. 7. 8.]
 [8. 7. 6. 5. 4. 3.]]
[3. 4. 5. 6. 7. 8.]
[8. 7. 6. 5. 4. 3.]
3.0
4.0
5.0
6.0
7.0
8.0
8.0
7.0
6.0
5.0
4.0
3.0


In [62]:
# Matrix product

A=np.arange(0,9).reshape(3,3)

print(A)

B=np.ones((3,3),dtype=int)

print(B)

print(np.dot(A,B))

print(A.dot(B))

print(B.dot(A))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 3  3  3]
 [12 12 12]
 [21 21 21]]
[[ 3  3  3]
 [12 12 12]
 [21 21 21]]
[[ 9 12 15]
 [ 9 12 15]
 [ 9 12 15]]


In [65]:
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())

0
4
2.0
1.4142135623730951
10


In [90]:
#Slicing
h=np.arange(3,20)
print(h)
print(h[-1])
print(h[1])
print(h[-5:-1])
print(h[1:-1])
print(h[:-1])
print(h[:])
print(h[::])
print(h[::-1])
print(h[::-3])
print(h[2:15:2])
print(h[2:-10:2])
print(h[-10:15:2])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
19
4
[15 16 17 18]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3]
[19 16 13 10  7  4]
[ 5  7  9 11 13 15 17]
[5 7 9]
[10 12 14 16]


In [92]:
print(h[[1,-1,0]])
print(A)

[ 4 19  3]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [101]:
print(A[2,1])
print(A[2,2])
print(A[0,2])
print(A[1:,1:])
print(A[2,1:])
print(A[1,1:])
print(A[::-1,::-1])
print(A[::-1,:])

7
8
2
[[4 5]
 [7 8]]
[7 8]
[4 5]
[[8 7 6]
 [5 4 3]
 [2 1 0]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [103]:

print(A)
A<3

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])